version: '3'

services:
  nginx:
    container_name: nginx
    image: ohttps/ohttps-nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      PUSH_NODE_ID: ${ohttps-id}
      PUSH_NODE_TOKEN: ${ohttps-token}
    volumes:
      - /var/www:/var/www
      - ./certificates:/etc/nginx/certificates
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
